version: "3"

volumes:
  app_prod:
    name: app_prod
  front_prod:
    name: front_prod
  app_prod_db:
    name: app_prod_db
  redis_prod_db:
    name: redis_prod_db

services:
  app_prod:
    container_name: app_prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - app_prod:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - front_prod
      - postgres
      - redis

  front_prod:
    container_name: front_prod
    build:
      context: .
      dockerfile: front.Dockerfille.prod
    volumes:
      - front_prod:/front
    ports:
      - "8080:8080"

  postgres:
    container_name: app-prod-db
    image: postgres
    volumes:
      - app_prod_db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}


  redis:
    container_name: redis_prod_db
    image: redis:6.0
    volumes:
      - redis_prod_db:/data/redis
    ports:
      - "6379:6379"

