FROM node:12.18.3

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
RUN npm install -g @angular/cli@10.1.3
RUN npm install -g nx
COPY . .

RUN npm run build:api

CMD ["node", "dist/apps/api/main.js"]

EXPOSE 3000
