export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const RECEIVE_CONTACT_LIST = 'CONTACT_LIST';

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';