export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const RECEIVE_CONTACT_LIST = 'CONTACT_LIST';

export const RECEIVE_NAME = 'RECEIVE_NAME';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';